apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-interview-go
resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/secret.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
